services:
  postgres:
    container_name: webhooks_database
    image: postgres:17
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: webhooks
    ports:
      - "5432:5432"
